// Generated by CoffeeScript 1.3.3
var helpers;

helpers = function(app) {
  var link, urls, _i, _len, _ref;
  urls = [];
  _ref = app.locals.menu;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    link = _ref[_i];
    urls.push(link.url);
  }
  app.generate_xml_sitemap = function(urls) {
    var freq, i, priority, root_path, xml;
    urls = urls || ["about.html", "javascript.html", "css.html", "html5.html"];
    root_path = "http://www.vladvuj.com";
    priority = 0.5;
    freq = "monthly";
    xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">";
    for (i in urls) {
      xml += "<url>";
      xml += "<loc>" + root_path + urls[i] + "</loc>";
      xml += "<changefreq>" + freq + "</changefreq>";
      xml += "<priority>" + priority + "</priority>";
      xml += "</url>";
      i++;
    }
    xml += "</urlset>";
    return xml;
  };
  return app.get("/sitemap.xml", function(req, res) {
    var sitemap;
    sitemap = app.generate_xml_sitemap(urls);
    res.header('Content-Type', 'text/xml');
    return res.send(sitemap);
  });
};

module.exports = helpers;
