// Generated by CoffeeScript 1.3.3
var app, assets, express, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.use(app.router);

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return resp.render('index');
});

require('./routes')(app);

require('./helpers')(app);

app.get("*", function(req, res) {
  return res.render('404', {
    title: "404 page"
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 4000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
