// Generated by CoffeeScript 1.3.3
var app, assets, express, fp, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

fp = require('feedparser');

app = express();

app.use(assets());

app.use(express["static"](process.cwd() + '/public'));

app.use(app.router);

app.set('view engine', 'jade');

app.get('/', function(req, resp) {
  return fp.parseUrl('http://blog.vladvuj.com/atom.xml', function(err, meta, articles) {
    if (err) {
      return console.error(err);
    }
    return resp.render('index', {
      articles: articles
    });
  });
});

app.configure('development', function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  return app.use(express.errorHandler());
});

require('./routes')(app);

require('./helpers')(app);

app.get("*", function(req, res) {
  return res.render('404', {
    title: "404 page"
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 4001;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
