// Generated by CoffeeScript 1.3.3
var routes;

routes = function(app) {
  app.locals({
    title: "Welcome to online portfolio of web developer Vladimir Vujosevic",
    menu: ["stream", "work", "about", "contact", "blog"]
  });
  return app.get('/stream', function(req, res) {
    return res.render("stream", {
      title: 'it\'s the stream'
    });
  });
};

module.exports = routes;
