// Generated by CoffeeScript 1.3.3
var routes;

routes = function(app) {
  app.locals({
    title: "Welcome to online portfolio of web developer Vladimir Vujosevic",
    menu: [
      {
        text: "stream",
        url: "/stream"
      }, {
        text: "work",
        url: "/work"
      }, {
        text: "about",
        url: "/about"
      }, {
        text: "contact",
        url: "/contact"
      }, {
        text: "blog",
        url: "http://blog.vladvuj.com"
      }
    ]
  });
  app.get('/stream', function(req, res) {
    return res.render("stream", {
      title: 'it\'s the stream'
    });
  });
  app.get('/work', function(req, res) {
    return res.render("work", {
      title: 'it\'s my work'
    });
  });
  app.get('/about', function(req, res) {
    return res.render("about", {
      title: 'it\'s about me page'
    });
  });
  return app.get('/contact', function(req, res) {
    return res.render("contact", {
      title: 'it\'s contact me page'
    });
  });
};

module.exports = routes;
